/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/yBhF0ghSnmy
 */
import Link from "next/link"

export function L2() {
  return (
    <div className="flex flex-col min-h-screen">
      <header className="px-4 lg:px-6 h-14 flex items-center">
        <Link className="flex items-center justify-center" href="#">
          <TreesIcon className="h-6 w-6" />
          <span className="sr-only">Holzhandlung</span>
        </Link>
        <nav className="ml-auto flex gap-4 sm:gap-6">
          <Link className="text-sm font-medium hover:underline underline-offset-4" href="#">
            Lieferprogramm
          </Link>
          <Link className="text-sm font-medium hover:underline underline-offset-4" href="#">
            Galerie
          </Link>
          <Link className="text-sm font-medium hover:underline underline-offset-4" href="#">
            Umwelt
          </Link>
          <Link className="text-sm font-medium hover:underline underline-offset-4" href="#">
            Holzarten
          </Link>
          <Link className="text-sm font-medium hover:underline underline-offset-4" href="#">
            Service
          </Link>
        </nav>
      </header>
      <main className="flex-1">
        <section className="w-full pt-12 md:pt-24 lg:pt-32 border-y">
          <div className="px-4 md:px-6 space-y-10 xl:space-y-16">
            <div className="grid max-w-[1300px] mx-auto gap-4 px-4 sm:px-6 md:px-10 md:grid-cols-2 md:gap-16">
              <div>
                <h1 className="lg:leading-tighter text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl xl:text-[3.4rem] 2xl:text-[3.75rem]">
                  Entdecken Sie die Welt des Holzes
                </h1>
              </div>
              <div className="flex flex-col items-start space-y-4">
                <p className="mx-auto max-w-[700px] text-gray-500 md:text-xl dark:text-gray-400">
                  Erkunden Sie unsere vielfältige Auswahl an hochwertigen Holzprodukten und erfahren Sie mehr über die
                  Vorteile und Anwendungsmöglichkeiten von Holz.
                </p>
                <div className="space-x-4">
                  <Link
                    className="inline-flex h-9 items-center justify-center rounded-md bg-gray-900 px-4 py-2 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300"
                    href="#"
                  >
                    Erfahren Sie mehr
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
      <footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t">
        <p className="text-xs text-gray-500 dark:text-gray-400">© 2024 Holzhandlung. Alle Rechte vorbehalten.</p>
        <nav className="sm:ml-auto flex gap-4 sm:gap-6">
          <Link className="text-xs hover:underline underline-offset-4" href="#">
            Kontakt
          </Link>
          <Link className="text-xs hover:underline underline-offset-4" href="#">
            Partner
          </Link>
          <Link className="text-xs hover:underline underline-offset-4" href="#">
            AGB
          </Link>
          <Link className="text-xs hover:underline underline-offset-4" href="#">
            Impressum
          </Link>
        </nav>
      </footer>
    </div>
  )
}


function TreesIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M10 10v.2A3 3 0 1 8.9 16v0H5v0h0a3 1-1-5.8V10a3 6 0Z" />
      <path d="M7 16v6" />
      <path d="M13 19v3" />
      <path d="M12 19h8.3a1 1 0 .7-1.7L18 14h.3a1 .7-1.7L16 9h.2a1 .8-1.7L13 3l-1.4 1.5" />
    </svg>
  )
}
